### PR TITLE
Upload Avatar to cloudinary in new folder and display on profile

### PR DESCRIPTION
**Pull request by Calvin087**
Screenshot 2022-03-02 at 21 34 52

### CODE REVIEW

**Review by robertcach — COMMENTED** [review]
@Calvin087  In the user > profile.hbs, the src of the image shouldn't be 
"{{currentUser.images}}"? That is the name of the input in register form.

This is the acctually code:
avatar

**Comment by Calvin087** [comment]
> @Calvin087 In the user > profile.hbs, the src of the image shouldn't be "{{currentUser.images}}"? That is the name of the input in register form.
> 
> This is the acctually code: avatar

Good point, pero yo creo currentUser viene de locals.currentUser (passport magic?)

Entonces si console.log(currentUser etc), vemos el user con avatarImg, desde user.models
Screenshot 2022-03-03 at 17 54 57

**Comment by robertcach** [comment]
@Calvin087 lo del currenterUser lo entiendo, pero entonces aquí por qué el input de auth/register.hbs tiene como nombre "images"? 
image

**Comment by Calvin087** [comment]
@robertcach ok he cambiado.

**Comment by robertcach** [comment]
@Calvin087 por mí OK para hacer merge a esta pull : )

**Comment by Calvin087** [comment]
review complete, merging

**Pull request merged**
